# Generated by Django 3.0.6 on 2020-06-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['email'],
            },
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['email'], name='newsletter__email_350e42_idx'),
        ),
    ]
