# Generated by Django 3.0.6 on 2020-07-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='newsletter',
            name='newsletter__email_350e42_idx',
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['email'], name='newsletters_email_d3a4d3_idx'),
        ),
    ]
