# Generated by Django 3.0.6 on 2020-07-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_auto_20200708_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
