# Generated by Django 3.0.6 on 2020-07-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_auto_20200708_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealer',
            options={},
        ),
    ]
