# Generated by Django 3.0.6 on 2020-07-08 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0006_auto_20200708_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='dealer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
