# Generated by Django 3.0.6 on 2020-05-29 16:35

from django.db import migrations


def populate_colors(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Color = apps.get_model("cars", "Color")
    db_alias = schema_editor.connection.alias
    Color.objects.using(db_alias).bulk_create([
        Color(name="Green"),
        Color(name="Red"),
        Color(name="Blue"),
        Color(name="White"),
        Color(name="Black")
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0002_auto_20200612_1157'),
    ]

    operations = [
        migrations.RunPython(populate_colors)
    ]
