# Generated by Django 3.0.6 on 2020-06-17 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_populate_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ('category',),
            },
        ),
        migrations.AddField(
            model_name='car',
            name='capacity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.Color'),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_power_kw',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.CharField(default='Rotary', max_length=15),
        ),
        migrations.AddField(
            model_name='car',
            name='first_reg_data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='Otto', max_length=15),
        ),
        migrations.AddField(
            model_name='car',
            name='gear_case',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='car',
            name='population_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='sitting_place',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['category'], name='cars_proper_categor_e1769a_idx'),
        ),
        migrations.AddField(
            model_name='car',
            name='properties',
            field=models.ManyToManyField(to='cars.Property'),
        ),
    ]
