# Generated by Django 3.0.6 on 2020-07-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20200617_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='public_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('published', 'Published'), ('sold', 'Sold'), ('archived', 'Archived'), ('wait for publish', 'Wait for publish')], default='pending', max_length=16),
        ),
    ]
